spring:
  application:
    name: customer-microservice
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/customer_db}
      auto-index-creation: false

server:
  port: ${SERVER_PORT:8091}
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    com.corhuila: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

