spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRESQL_HOST:host.docker.internal}:${POSTGRESQL_DB_PORT:5432}/${PRODUCT_DB_NAME:product_db}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRESQL_DB_USERNAME:change_me_pg_user}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRESQL_DB_PASSWORD:change_me_pg_password}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/}

logging:
  level:
    root: INFO
    com.corhuila.microservices: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/product-microservice.log
    max-size: 10MB
    max-history: 30

server:
  port: 8092