services:
  mongodb:
    restart: unless-stopped

  postgresql:
    restart: unless-stopped

  config-server:
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=native,docker,release

  discovery-server:
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker,release

  customer-microservice:
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker,release

  product-microservice:
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker,release

  cart-microservice:
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker,release

