services:
  config-server:
    environment:
      - SPRING_PROFILES_ACTIVE=native,docker,dev

  discovery-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev

  api-gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev

  analytics-service:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev

  customer-microservice:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev
    networks:
      - microservices
      - database

  product-microservice:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev

  cart-microservice:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev
    networks:
      - microservices
      - database

  auth-microservice:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev

  purchase-microservice:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev

  invoice-microservice:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev

networks:
  database:
    external: true
    name: ${DATABASE_NETWORK_NAME:-pos-db-dev_default}

